/**
 ******************************************************************************
  * @file    sd_spi.h
  * @brief   This file contains the common defines and functions prototypes for
  *          the sd_spi driver implementation
  ******************************************************************************
  * Portions copyright (C) 2014, ChaN, all rights reserved.
  * Portions copyright (C) 2017, kiwih, all rights reserved.
  *
  * This software is a free software and there is NO WARRANTY.
  * No restriction on use. You can use, modify and redistribute it for
  * personal, non-profit or commercial products UNDER YOUR RESPONSIBILITY.
  * Redistributions of source code must retain the above copyright notice.
  *
  ******************************************************************************
  */

#ifndef _USER_DISKIO_SPI_H
#define _USER_DISKIO_SPI_H

#include "stm32l4xx_hal.h"
#include "integer.h" //from FatFs middleware library

/* SD card SPI handle - SPI1 is connected to the SD card */
#define SD_SPI_HANDLE hspi1
#include "diskio.h" //from FatFs middleware library
#include "ff_gen_drv.h" //from FatFs middleware library

typedef struct {
  uint8_t stat;
  uint8_t card_type;
  uint8_t stage;
  uint8_t last_cmd;
  uint8_t last_resp;
  uint8_t last_token;
  uint8_t last_hal_status;
  uint8_t reserved;
  uint32_t last_arg;
  uint32_t last_sector;
  uint32_t spi_error;
  uint16_t last_count;
  int last_result;
} SD_SPI_Diag_t;

//we define these as inline because we don't want them to be actual function calls (they get "called" from the cubemx autogenerated user_diskio file)
//we define them as extern because they are defined in a separate .c file to user_diskio.c (which #includes this .h file)

extern DSTATUS USER_SPI_initialize (BYTE pdrv);
extern DSTATUS USER_SPI_status (BYTE pdrv);
extern void USER_SPI_reset (void);
extern const SD_SPI_Diag_t *USER_SPI_diag (void);
extern const char *USER_SPI_diag_stage_name (uint8_t stage);
extern DRESULT USER_SPI_read (BYTE pdrv, BYTE *buff, DWORD sector, UINT count);
#if _USE_WRITE == 1
  extern DRESULT USER_SPI_write (BYTE pdrv, const BYTE *buff, DWORD sector, UINT count);
#endif /* _USE_WRITE == 1 */
#if _USE_IOCTL == 1
  extern DRESULT USER_SPI_ioctl (BYTE pdrv, BYTE cmd, void *buff);
#endif /* _USE_IOCTL == 1 */

#endif /* #define _USER_DISKIO_SPI_H */
